In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
data = pd.read_csv('car.data')
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [6]:
X = data[[
    'buying',
    'maint',
    'safety'
]].values

y = data[['class']]

In [9]:
#Conversions using labelEncoder
#x

le = LabelEncoder()

for i in range(len(X[0])):
    X[:,i] = le.fit_transform(X[:,i])
    
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [10]:
#Conversion Y using mapping

Label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}

y['class'] = y['class'].map(Label_mapping)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


C:\Users\kaust\AppData\Local\Temp/ipykernel_8544/1064424802.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(Label_mapping)


In [12]:
# Model Creation
knn = neighbors.KNeighborsClassifier(n_neighbors = 25, weights = 'uniform')

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [18]:
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)
accuracy = metrics.accuracy_score(y_test, predictions)

print("Predictions :", predictions)
print("Accuracy :", accuracy)

Predictions : [0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1 3 0 3 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0
 0 0 1 0 0 0 3 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 3 1 0 1 1 1 0 0
 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 0 0 2 2 0 0 0 3 0 0 0
 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0
 0 3 1 0 3 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 2 0 0 0 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 3 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 3 0 1 1 1 3 2 0 1 0 0 0 0 0 0 0 0
 0 0 0 1 3 0 0 0 0 1 1 0 0 1 0 0 0 0 0 2 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 0 0 3]
Accuracy : 0.7543352601156069


C:\Users\kaust\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
